spring.application.name=photoframestore
spring.datasource.url=${jdbc:postgresql://dpg-d6eo3cngi27c73fgcjbg-a.singapore.render.com:5432/photoframestore_db}
spring.datasource.username=${santosh}
spring.datasource.password=${sunny@123@143}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8082
server.servlet.session.timeout=15m

spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=classpath:/static/
