spring.application.name=photoframestore

spring.datasource.url=jdbc:mysql://localhost:3306/photoframestore
spring.datasource.username=root
spring.datasource.password=Sunny@123@143

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}
server.servlet.session.timeout=15m

spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=classpath:/static/

